class Hotel {
  int id;
  String name;
  String desc;
  String price;
  String imageUrl;

  Hotel({
    required this.id,
    required this.name,
    required this.desc,
    required this.price,
    required this.imageUrl,
  });
}

final List<Hotel> hotels = [
  Hotel(
    id: 1,
    name: "Crowne Plaza Nairobi Airport",
    desc: "Luxury comfort just minutes from JKIA with world-class dining and service.",
    price: "KES 22,500/night",
    imageUrl: "assets/images/hotels/1.jpg",
  ),
  Hotel(
    id: 2,
    name: "Palacina The Residence & The Suites",
    desc: "Elegant boutique living with timeless luxury in the heart of Nairobi.",
    price: "\$200/night",
  imageUrl: "assets/images/hotels/2.jpg",
  ),
  Hotel(
    id: 3,
    name: "Villa Rosa Kempinski",
    desc: "Five-star luxury blending European flair with Kenyan warmth.",
    price: "\$250/night",
    imageUrl: "assets/images/hotels/3.webp",
  ),
  Hotel(
    id: 4,
    name: "Hemingways Nairobi",
    desc: "An oasis of tranquility with personalized butler service.",
    price: "KES 60,000/night",
    imageUrl: "assets/images/hotels/4.jpg",

  ),
  Hotel(
    id: 5,
    name: "Radisson Blu Hotel Nairobi Upper Hill",
    desc: "Modern elegance with skyline views and premium comfort.",
    price: "KES 27,000/night",
    imageUrl: "assets/images/hotels/5.webp",
  ),
  Hotel(
    id: 6,
    name: "Fairmont The Norfolk",
    desc: "Historic charm and luxury since 1904 in central Nairobi.",
    price: "KES 33,000/night",
    imageUrl: "assets/images/hotels/6.webp",
  ),
  Hotel(
    id: 7,
    name: "Sankara Nairobi, Autograph Collection",
    desc: "Stylish urban retreat with rooftop dining and world-class art.",
 price: "KES 31,500/night",
    imageUrl: "assets/images/hotels/7.webp",
  ),
  Hotel(
    id: 8,
    name: "Tribe Hotel, Nairobi",
    desc: "Bold, artistic design with luxury and authentic Kenyan culture.",
    price: "KES 34,500/night",
    imageUrl: "assets/images/hotels/8.webp",
  ),
  Hotel(
    id: 9,
    name: "The Boma Nairobi",
    desc: "Modern luxury with warm African hospitality and top amenities.",
  price: "KES 24,000/night",
    imageUrl: "assets/images/hotels/9.webp",
  ),
  Hotel(
    id: 10,
    name: "Hilton Garden Inn Nairobi Airport",
    desc: "Comfort and convenience just minutes from the airport.",
   price: "KES 21,000/night",
    imageUrl: "assets/images/hotels/10.webp",
  ),
  Hotel(
    id: 11,
    name: "Eka Hotel Nairobi",
    desc: "Chic and convenient stay close to Nairobi’s attractions.",
    price: "KES 19,500/night",
    imageUrl: "assets/images/hotels/11.webp",
  ),
  Hotel(
    id: 12,
    name: "Best Western Plus Meridian Hotel",
    desc: "Affordable comfort with modern amenities in the city center.",
    price: "KES 13,500/night",
    imageUrl: "assets/images/hotels/12.webp",
  ),
  Hotel(
    id: 13,
    name: "Four Points by Sheraton Nairobi Airport",
    desc: "Seamless airport access with luxury and modern comfort.",
    price: "KES 24,000/night",
    imageUrl: "assets/images/hotels/13.webp",
  ),
  Hotel(
    id: 14,
    name: "The Sarova Stanley",
    desc: "Iconic Nairobi landmark hotel with heritage luxury.",
   price: "KES 28,500/night",
    imageUrl: "assets/images/hotels/14.jpg",
  ),
  Hotel(
    id: 15,
    name: "Mövenpick Hotel & Residences Nairobi",
    desc: "Upscale hotel with panoramic city views and refined dining.",
    price: "KES 30,000/night",
    imageUrl: "assets/images/hotels/15.webp",
  ),
  Hotel(
    id: 16,
    name: "ibis Styles Nairobi Westlands",
    desc: "Trendy and budget-friendly stay in the vibrant Westlands.",
 price: "KES 12,000/night",
    imageUrl: "assets/images/hotels/16.webp",
  ),
  Hotel(
    id: 17,
    name: "Mercure Nairobi Upper Hill",
    desc: "Comfortable business-friendly hotel in Upper Hill.",
    price: "KES 16,500/night",
    imageUrl: "assets/images/hotels/17.webp",
  ),
  Hotel(
    id: 18,
    name: "Nairobi Serena Hotel",
    desc: "Classic five-star luxury with serene gardens and pools.",
    price: "KES 36,000/night",
    imageUrl: "assets/images/hotels/18.webp",
  ),
  Hotel(
    id: 19,
    name: "The Concord Hotel & Suites",
    desc: "Spacious suites with elegance and modern luxury.",
    price: "KES 25,500/night",
    imageUrl: "assets/images/hotels/19.webp",
  ),
  Hotel(
    id: 20,
    name: "Safari Park Hotel",
    desc: "Resort-style hotel with lush gardens and cultural shows.",
    price: "KES 22,500/night",
    imageUrl: "assets/images/hotels/20.webp",
  ),
  Hotel(
    id: 21,
    name: "Boma Inn Nairobi",
    desc: "Affordable comfort with easy access to central Nairobi.",
    price: "KES 13,500/night",
    imageUrl: "assets/images/hotels/21.avif",
  ),
  Hotel(
    id: 22,
    name: "Tamarind Tree Hotel Nairobi",
    desc: "Vibrant modern hotel near Wilson Airport and attractions.",
    price: "KES 18,000/night",
    imageUrl: "assets/images/hotels/22.webp",
  ),
  Hotel(
    id: 23,
    name: "The Heron Portico",
    desc: "Charming boutique hotel with warm hospitality.",
    price: "KES 15,000/night",
    imageUrl: "assets/images/hotels/23.webp",
  ),
  Hotel(
    id: 24,
    name: "Park Inn by Radisson Nairobi Westlands",
    desc: "Contemporary hotel with vibrant dining and comfort.",
    price: "KES 16,500/night",
    imageUrl: "assets/images/hotels/24.webp",
  ),
  Hotel(
    id: 25,
    name: "La Mada Hotel",
    desc: "Tranquil stay surrounded by Nairobi’s green forest.",
    price: "KES 21,000/night",
    imageUrl: "assets/images/hotels/25.webp",
  ),
  Hotel(
    id: 26,
    name: "DoubleTree by Hilton Nairobi Hurlingham",
    desc: "Contemporary elegance with Hilton comfort.",
    price: "KES 24,000/night",
    imageUrl: "assets/images/hotels/26.webp",
  ),
  Hotel(
    id: 27,
    name: "Weston Hotel",
    desc: "Elegant stay with great dining and event spaces.",
    price: "KES 22,500/night",
    imageUrl: "assets/images/hotels/27.webp",
  ),
  Hotel(
    id: 28,
    name: "Melili Hotel",
    desc: "Affordable modern hotel with cozy interiors.",
    price: "KES 10,500/night",
    imageUrl: "assets/images/hotels/28.webp",
  ),
  Hotel(
    id: 29,
    name: "Town Lodge Upper Hill Nairobi",
    desc: "Smart and budget-friendly business hotel.",
    price: "KES 12,750/night",
    imageUrl: "assets/images/hotels/29.webp",
  ),
  Hotel(
    id: 30,
    name: "Ole Sereni Hotel Nairobi",
    desc: "Unique views over Nairobi National Park with luxury comfort.",
    price: "KES 27,000/night",
    imageUrl: "assets/images/hotels/30.jpg",
  ),
];
